### ISSUE TITLE
Ignore transitive dependencies

### ISSUE THREAD

**Issue by JP95Git** [f4lco/libyear-gradle-plugin#15]
I have a library in my build.gradle with this configuration:
```
repositories {
  mavenCentral()
  maven {
    url "https://jitpack.io"
  }
}

dependencies {
  implementation("com.github.Bombe:jFCPlib:v0.1.6")
}
```
This library is the recent version, but it requires a transitive dependency named "Guava". libyear complaines that Guava is outdated, but there is nothing I can do to fix this, because the author of jFCPlib seems to have abandoned the project. So it would be nice if it is possible to exclude such transitive dependencies from libyear, if possible via settings.

**Comment by Breefield** [comment]
I'm working on adding this because I want it too.

**Comment by f4lco** [comment]
Thank you @breefield I’d be looking forward to a PR. Optionally limiting the report to “primary” / “first tier” / “non transitive” dependencies would make a useful addition to the plugin.

**Comment by Breefield** [comment]
Ah yes, let me swap this boolean with an integer and then I'll modify the recursion logic to track what tier the dep is at to ignore.

**Comment by Breefield** [comment]
@f4lco the PR is ready to review; I’ve added a few other feature PRs I’d love consideration of!

**Comment by JP95Git** [comment]
Thanks, it works.

I used this settings in build.gradle:
```
plugins {
	id "java"
	id "com.libyear.libyear-gradle-plugin" version "0.2.0"
}

libyear {
	failOnError = false
}
```
